### ISSUE TITLE
Unable to install GraalVM CE 19.1.0 on macOS

### ISSUE THREAD

**Issue by rsvoboda** [sdkman/sdkman-db-migrations#126] opened 2019-07-03 06:10 UTC
Unable to install GraalVM CE 19.1.0 on macOS (Mojave 10.14.5)
Works well on Linux machine ...

```
sdk install java 19.1.0-grl
tr: Illegal byte sequence

Downloading: java 19.1.0-grl

In progress...

######################################################################## 100.0%

Repackaging Java 19.1.0-grl...
-bash: cd: /Users/rsvoboda/.sdkman/tmp/out/*/Contents: No such file or directory
mv: rename Home to /Users/rsvoboda/.sdkman/tmp/Java-19.1.0-grl: No such file or directory

zip error: Nothing to do! (try: zip -qyr /Users/rsvoboda/.sdkman/tmp/.zip . -i Java-19.1.0-grl)

Done repackaging...
Cleaning up residual files...
mv: rename /Users/rsvoboda/.sdkman/tmp/.zip to /Users/rsvoboda/.sdkman/archives/java-19.1.0-grl.zip: No such file or directory
unzip:  cannot find or open /Users/rsvoboda/.sdkman/archives/java-19.1.0-grl.zip, /Users/rsvoboda/.sdkman/archives/java-19.1.0-grl.zip.zip or /Users/rsvoboda/.sdkman/archives/java-19.1.0-grl.zip.ZIP.
rm: /Users/rsvoboda/.sdkman/archives/java-19.1.0-grl.zip: No such file or directory

Stop! The archive was corrupt and has been removed! Please try installing again.
```

**Comment by rsvoboda** [comment] 2019-07-03 06:25
Hmm, Linux "works" as it installs binaries, but those binaries are for macOS :(

https://github.com/sdkman/sdkman-db-migrations/pull/125/files is wrong

**Comment by rsvoboda** [comment] 2019-07-03 06:27
Preparing PR

**Comment by marc0der** [comment] 2019-07-03 06:53
Also please use slack as per the contributor guidelines. Closing this issue as it is a data problem not a bug.

**Closed by marc0der** 2019-07-03 06:53 UTC

**Comment by rsvoboda** [comment] 2019-07-03 07:55
Ah, didn't notice contribution notes in https://github.com/sdkman/sdkman-db-migrations/blob/master/README.md

I guess you are referring to https://github.com/sdkman/sdkman-cli/blob/master/CONTRIBUTING.md

**Comment by marc0der** [comment] 2019-07-03 08:04
Looks like @ilopmar beat you!

**Comment by rsvoboda** [comment] 2019-07-03 08:23
yeah, np at all :) 

Just a note - I had to run `sdk flush archives` on my Linux machine where macOS based binary was downloaded before the links fix. Otherwise you will see "Found a previously downloaded java 19.1.0-grl archive. Not downloading it again..."
